### PR TITLE
Currency issue

### PR DESCRIPTION
**Pull request by djeada**
It would be preferable to adopt a more widely accepted currency, such as the euro.

### CODE REVIEW

**Review by waelsy123 — APPROVED** [review]
Looks good to me, thanks for contribution!

It will be great to add a drop down menu to select currency

**Review by djeada — COMMENTED** [review]
README is used to describe the project. This version of the README is lays the foundation for all other versions. It shoud be updated as the project evolves. There is no need to strictly follow the format of this file.

**Comment by waelsy123** [comment]
@djeada I think you have a minor misunderstanding concept of the game :D, have you tried to visit the demo?

**Comment by djeada** [comment]
I already included the plans for the second release.

**Review by waelsy123 — APPROVED** [review]

**Pull request merged**
